config/routes.rb
Rails.application.routes.draw do

  root 'items#index'

  get 'likes/create'
  get 'likes/destroy'

  post 'users/card_create',   to: 'users#card_create'
  delete 'users/card_delete', to: 'users#card_delete'

  match 'category_select',       to: 'items#category_select',       via: [:get, :post]
  match 'child_category_select', to: 'items#child_category_select', via: [:get, :post]

  devise_for :users, controllers: {
    registrations:      'users/registrations',
    sessions:           'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get  'to_signup',      to: 'users/registrations#to_signup'
    post 'signup/profile', to: 'users/registrations#profile'
    post 'signup/address', to: 'users/registrations#address'
    post 'signup/credit',  to: 'users/registrations#credit'
  end

  resources :users,except: :show do
    get :logout,               on: :collection
    get :payment_method,       on: :collection
    get :card_registration,    on: :collection
    get :indentification,      on: :collection
    get :trading,              on: :collection
    get :purchased,            on: :collection
    get :exhibition,           on: :collection
    get :seller_trading,       on: :collection
    get :sold_page,            on: :collection
    get :notification,         on: :collection
    get :todo,                 on: :collection
    get :individual,           on: :member
    resources :likes,     only: :index
    resources :addresses, only: [:edit, :update]
    resources :lates,     only: :index do
      get :great,              on: :collection
      get :good,               on: :collection
      get :poor,               on: :collection
    end
    member do
     get :following, :followers
    end
  end

  scope :profiels do
    resources :users, only: :show
  end

  resources :items do
    get  :buy,                 on: :collection
    get  :all_categories_show, on: :collection
    get  :item_search_result,  on: :collection
    get  :buy,                 on: :member
    post :pay,                 on: :member
    get  :trading_message,     on: :member
    post :trading_page,        on: :member
    post :message,             on: :member
    post :late,                on: :member
    resources :comments, only: [:create, :destroy]
    resources :likes,    only: [:create, :destroy]
  end

  resources :categories, only: :show do
    get :child_category,       on: :collection
    get :grand_child_category, on: :collection
  end

  resources :brands, only: :show do
    get :brand_show,          on: :member
  end

  resources :relationships, only: [:create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:omniauthable

  mount_uploader :avatar, ImageUploader

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :card_month
  belongs_to_active_hash :card_year
  belongs_to_active_hash :birth_year_select


  has_many :items
  has_one :address
  has_one :profile
  has_many :comments ,dependent: :delete_all
  has_many :messages, dependent: :delete_all
  has_many :lates, dependent: :delete_all


  has_many :active_relationships,class_name:  "Relationship", foreign_key: "follower_id", dependent: :destroy

  has_many :passive_relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy

  has_many :following, through: :active_relationships, source: :following

  has_many :followers, through: :passive_relationships, source: :follower


  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :nickname,        presence: true, length: { in: 1..20 }, uniqueness: true
  validates :email,           presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  validates :password,        presence: true, length: { in: 6..128 }, confirmation: true, on: :create

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        nickname:     auth.info.name,
        email:    auth.info.email,
        token:    auth.credentials.token,
        password: Devise.friendly_token[0, 20],
      )

      address = Address.new(
        user_id:        user.id,
      )
      address.save!(validate: false)
      Profile.create(
        user_id:         user.id,
      )
    end
    user
  end

  def follow(other_user)
    active_relationships.create(following_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(following_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    callback_from :facebook
  end

  def google_oauth2
    callback_from :google_oauth2
  end


  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      flash[:notice] = I18n.t("devise.omniauth_callbacks.success", kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true
class Users::RegistrationsController < Devise::RegistrationsController
  require "payjp"
  require "date"
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :authenticate_user!, expect: :credit

  before_action :set_search,   only: [:edit]
  before_action :set_category, only: [:edit]

  prepend_before_action :check_captcha, only: :create
  prepend_before_action :customize_sign_up_params, only: [:create, :credit]
  protect_from_forgery except: [ :card_create, :card_delete, :payment_method, :card_registration]

  def to_signup
  end

  def create
    check = true

    session[:nickname]              = params[:session][:nickname]
    session[:email]                 = params[:session][:email]
    session[:password]              = params[:session][:password]
    session[:password_confirmation] = params[:session][:password_confirmation]

    @temporary = Temporary.create(
      nickname:              session[:nickname],
      email:                 session[:email],
      password:              session[:password],
      password_confirmation: session[:password_confirmation],
    )

    @error = []
    @error << check_name(session[:nickname])
    @error << check_email(session[:email])
    @error = @error.compact

    check = @temporary.save(context: :new_user)

    if (check == false) || (@error.empty? == false) then
      @temporary.destroy
      render :new
    end

    session[:user_id] = @temporary.id
  end

  def profile

    session[:first_name]      = params[:session][:first_name]
    session[:last_name]       = params[:session][:last_name]
    session[:first_name_kana] = params[:session][:first_name_kana]
    session[:last_name_kana]  = params[:session][:last_name_kana]
    session[:birth_year]      = params[:session][:birth_year]
    session[:birth_month]     = params[:session][:birth_month]
    session[:birth_day]       = params[:session][:birth_day]

    @temporary = Temporary.find(session[:user_id])

    @temporary.update(
      first_name:       session[:first_name],
      last_name:        session[:last_name],
      first_name_kana:  session[:first_name_kana],
      last_name_kana:   session[:last_name_kana],
      birth_year:       session[:birth_year],
      birth_month:      session[:birth_month],
      birth_day:        session[:birth_day],
    )

    render :create unless @temporary.save(context: :profile_form)

  end

  def address
    check = true

    session[:post_number]   = params[:session][:post_number].gsub("-","")
    session[:prefecture_id] = params[:session][:prefecture_id]
    session[:city]          = params[:session][:city]
    session[:town]          = params[:session][:town]
    session[:building]      = params[:session][:building]
    session[:phone_number]  = params[:session][:phone_number].gsub("-","")

    @error = []
    @error << check_phone(session[:phone_number])
    @error = @error.compact

    @temporary = Temporary.find(session[:user_id])

    @temporary.update(
      post_number:   session[:post_number],
      prefecture_id: session[:prefecture_id],
      city:          session[:city],
      town:          session[:town],
      building:      session[:building],
      phone_number:  session[:phone_number],
    )

    check = @temporary.save(context: :address_form)

    if (check == false) || (@error.empty? == false) then
      @temporary.phone_number = nil
      @temporary.save
      render :profile
    end
  end

  def credit
    check = true

    session[:number]    = params[:session][:number].gsub("-","")
    session[:exp_month] = params[:session][:exp_month]
    session[:exp_year]  = params[:session][:exp_year]
    session[:cvc]       = params[:session][:cvc]

    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]

    begin
      Payjp::Token.create({
        card: {
          number: session[:number],
          cvc: session[:cvc],
          exp_month: session[:exp_month],
          exp_year: session[:exp_year]
        }},
        {
          "X-Payjp-Direct-Token-Generate": "true"
        })
    rescue
      check = false
      @error = []
      @error << "カードの登録に失敗しました"
      @error << check_number(session[:number])
      @error << check_select(session[:exp_year], session[:exp_month])
      @error << check_cvc(session[:cvc])
      @error = @error.compact
    end

    if check == true
      card = Payjp::Token.create({
        card: {
          number: session[:number],
          cvc: session[:cvc],
          exp_month: session[:exp_month],
          exp_year: session[:exp_year]
        }},
        {
          "X-Payjp-Direct-Token-Generate": "true"
        })
      customer = Payjp::Customer.create(
        email: session[:email],
        card: card
      )
      # userの正規登録
      @user = User.new(
        nickname:              session[:nickname],
        email:                 session[:email],
        password:              session[:password],
        password_confirmation: session[:password_confirmation],
      )

      @user.save

      sign_up(@user, current_user)
      if @user.save
        Temporary.find(session[:user_id]).destroy
      end

      # プロフィールの正規登録
      @profile = Profile.new(
        first_name:      session[:first_name],
        last_name:       session[:last_name],
        first_name_kana: session[:first_name_kana],
        last_name_kana:  session[:last_name_kana],
        birth_year:      session[:birth_year],
        birth_month:     session[:birth_month],
        birth_day:       session[:birth_day],
        user_id:         @user.id
      )
      @profile.save

      # 住所の正規登録
      @address = Address.new(
        post_number:   session[:post_number],
        prefecture_id: session[:prefecture_id],
        city:          session[:city],
        town:          session[:town],
        building:      session[:building],
        phone_number:  session[:phone_number],
        user_id:       @user.id
      )
      @address.save

      @user.update_attribute(:customer_id, customer.id)
    else
      render :address
    end
  end


  protected

  def customize_sign_up_params
    devise_parameter_sanitizer.permit :sign_up, keys: [:nickname, :email, :password, :password_confirmation, :remember_me]
  end

  def check_captcha
    self.resource = resource_class.new sign_up_params
    resource.validate
    unless verify_recaptcha(model: resource)
      respond_with_navigational(resource) { render :new }
    end
  end

  def check_name(nickname)
    nickname = User.where(nickname: nickname)
    return "このニックネームは使われています" if nickname.present?
  end

  def check_email(email)
    email    = User.where(email: email)
    return "このE-MAILは使われています" if email.present?
  end

  def check_phone(phone)
    phone = Address.where(phone_number: phone)
    return "この電話番号は使われています" if phone.present?
  end

  def check_number(number)
    return "カードナンバーは14桁から17桁で入力してください" if (number.length < 14) || (number.length > 17)
  end

  def check_select(exp_year, exp_month)
    date = Date.today
    date = "#{date.year}#{date.month}".to_i
    exp_select = "#{exp_year}#{exp_month}".to_i
    error = "有効期限が切れています" if exp_select < date
    error = "カードの有効期限を選択してください" if (exp_year == "2019") && (exp_month == "1")
    return error
  end

  def check_cvc(cvc)
    return "セキュリティコードの桁数が違います" if (cvc.length < 3) || (cvc.length > 4)
    return "セキュリティコードは数字のみで入力してください" unless cvc.match(/[0-9]/)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  prepend_before_action :check_captcha, only: [:create]
  prepend_before_action :customize_sign_in_params, only: [:create]

  protected

  def customize_sign_in_params
    devise_parameter_sanitizer.permit :sign_in, keys: [ :email, :password]
  end

  def check_captcha
    self.resource = resource_class.new sign_in_params
    resource.validate
    unless verify_recaptcha(model: resource)
      respond_with_navigational(resource) { render :new }
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
     user == current_user
  end
end

app/views/users/_follow_form.html.haml
- unless current_user?(@user)
  #follow_form
    - if current_user.following?(@user)
      = render 'unfollow'
    - else
      = render 'follow'

app/views/users/_unfollow.html.haml
= form_for(current_user.active_relationships.find_by(following_id: @user.id),html: { method: :delete }) do |f|
  = f.submit "フォロー解除", class: "btn btn-primary"

app/views/users/index.html.haml
- breadcrumb :users
= render 'shared/header'

%main.l-container.clearfix
  = render 'shared/l-side'
  .l-content
    %section.mypage-user-icon
      = link_to individual_user_path(@user) do
        %figure
          - if current_user.persisted? && current_user.avatar?
            = image_tag current_user.avatar.to_s, class: 'avatar_present_img'
          - else
            = image_tag "//static.mercdn.net/images/member_photo_noimage_thumb.png", alt: "", width: 60,height: "60"
        %h2.bold
          = @user.nickname
        .mypage-number
          %div
            評価
            %span.bold
              = @user.late_count
          %div
            出品数
            %span.bold
              = @user.items.count

    = render 'user-mypage-container'

    = render 'user-item-status'

= render 'shared/footer'

= render 'shared/sell-button'

app/views/users/payment_method.html.haml
- breadcrumb :payment_method
= render 'shared/header'

%main.l-container
  = render 'shared/l-side'
  .right-content
    %section.right-container
      %h2.right-container__title 支払い方法
      .right-container__inner
        %section
          .right-single-content
            %h3.right-container__sub-title
              クレジットカード一覧
              - if @card.present?
                %ul.right-container__card
                  %li
                    .users-card
                      %figure
                        = render 'shared/card-images'
                      .users-card__num
                        = "************" + @card.last4
                      = "0#{@card.exp_month} / #{@card.exp_year.to_s.slice(0..1).to_i}"
                      .users-card__exp
                        = link_to users_card_delete_path, method: :delete do
                          削除する
              - else
                .right-single-content
                  = link_to card_registration_users_path,class: "btn-default btn-red add-credit-card__link" do
                    %i.fa.fa-credit-card.add-credit-card__icon
                    クレジットカードを追加する
            .payment-method
              = link_to "https://www.mercari.com/jp/help_center/category/6/",target: "_blank", class: "payment-method__link" do
                %span.payment-method__text 支払い方法について
                %i.fa.fa-angle-right.payment-method__icon

= render 'shared/sell-button'
= render 'shared/footer'

app/views/users/trading_message.html.haml
= render 'shared/header'

%nav.bread-crumbs
  %ul
    %li{:itemscope => "", :itemtype => "http://data-vocabulary.org/Breadcrumb"}
      = link_to 'メルカリ', root_path
      = fa_icon 'angle-right'
    %li{:itemscope => "", :itemtype => "http://data-vocabulary.org/Breadcrumb"}
      = link_to 'マイページ', users_path
      = fa_icon 'angle-right'
    %li{:itemscope => "", :itemtype => "http://data-vocabulary.org/Breadcrumb"}
      = link_to "購入した商品 - 取引中", trading_users_path
      = fa_icon 'angle-right'
    %li{:itemscope => "", :itemtype => "http://data-vocabulary.org/Breadcrumb"}
      %span{:itemprop => "title"} 取引画面
%main.l-container.clearfix
  .l-content
    %section.l-chapter-container
      %h2.l-chapter-head 取引画面
      .transact-attention
        -# %h3
        -#   %i.fa.fa-clock-o
        -#   %span 発送をお待ちください
        -# %p 出品者からの発送通知をお待ちください。
        %h3
          %i.fa.fa-user-circle
          %span 受取評価をしてください
        %p 商品が発送されました。商品が到着したら、出品者の評価をしてください。
        -# %h3
        -#   %i.fa.fa-truck
        -#   %span 発送をしてください
        -# %p 商品が購入され支払いされました。商品の発送を行ってください。
        -# %h3
        -#   %i.fa.fa-check
        -#   %span 商品の発送を通知しました
        -# %p 購入者の受取確認と評価をしばらくお待ち下さい
      %ul.transact-guide.text-right
        %li
          %a{:href => "/jp/help_center/category/5/", :target => "_blank"}
            %span 商品が売れた後の流れ
            -# %span 購入した後の流れ
            %i.fa.fa-angle-right
        %li
          %a{:href => "/jp/help_center/category/5/", :target => "_blank"}
            %span 出品者のよくある質問
            -# %span 購入者のよくある質問　
            %i.fa.fa-angle-right

      %section.l-single-inner.yuuyuu-content
        %h3 配送状況
        %nav.progress-bar
          %ol.clearfix
            %li.active
              発送済み
              .progress-status
            %li
              輸送中
              .progress-status
            %li
              配達中
              .progress-status
            %li
              受取
              .progress-status
        %p 引受
        %p
          %span.bold
            ※ゆうゆうメルカリ便に関するお問い合わせは
            %a{:href => "https://www.mercari.com/jp/mypage/support/"}> こちら
            よりお願いします
          %br/
          （日本郵便には、直接お問い合わせされないようお願いします）


      %form.transact-form-review{:action => "https://www.mercari.com/jp/transaction/review/m18251864076/", :method => "POST"}
        %input{:name => "__csrf_value", :type => "hidden", :value => "548b8672d0a5998354cfac5c0af6823e6a1fd351fdac08492995fc979a866428bcdf5275bb3e1f5dce8399036f2f3b1d2edc82e5c7f7b893ca0525ae979de99fc"}/
        .checkbox-default
          %input#transaction_delivered{:name => "transaction_delivered", :type => "checkbox", :value => "1"}/
          %i.icon-check
          %label{:for => "transaction_delivered"} 商品の中身を確認しました。
        %ul.transact-review-list.clearfix
          %li
            %input#face1{:name => "fame", :type => "radio", :value => "good"}/
            .transact-review-icon
              %i.icon-good
              %label{:for => "face1"}
                良い
          %li
            %input#face2{:name => "fame", :type => "radio", :value => "normal"}/
            .transact-review-icon
              %i.icon-normal
              %label{:for => "face2"}
                普通
          %li
            %input#face3{:name => "fame", :type => "radio", :value => "bad"}/
            .transact-review-icon
              %i.icon-bad
              %label{:for => "face3"}
                悪い
        %p 評価のコメントを記入しましょう。
        %textarea.textarea-default{:name => "message", :placeholder => "コメントはなくても構いませんが、お礼のメッセージなどを書くと喜ばれます。"}
        %button.btn-default.btn-red{:disabled => "disabled", :type => "submit"}
          評価を投稿する

      -# .transact-button
      -#   %form{:action => "/jp/shipping/shipped/m46233963393/", :method => "POST", :novalidate => "novalidate"}
      -#     %input{:name => "__csrf_value", :type => "hidden", :value => "cc5da73d1f3563876c4598e97658e52fe75e6b090a79d6f4b4a3048073d34ba1f11545b99e1fbe4303d901cdfb9537c2c8033c59c247ba42eb58ce5d355ff35ef"}/
      -#     %button.btn-default.btn-red{:type => "submit"} 商品の発送をしたので、発送通知をする


      .message-container
        .message-content1
          .notification.notification-success
            %i.icon-close
          %ul.message-items
            %li.clearfix
              %a.message-user{:href => ""}
                %figure
                  %div
                    %img{:alt => "", :src => "//static.mercdn.net/images/member_photo_noimage_thumb.png"}/
                  %figcaption.bold
                    メルカリ二郎
              .message-body
                .message-body-text こんにちわ、この度はご購入ありがとうございます。発送終えましたらコメントさせてもらいます。
                .message-icons.clearfix
                  %time.message-icon-left
                    %i.fa.fa-clock-o
                    %span 46 秒前
                %i.icon-balloon
            %li.clearfix.message-self
              %a.message-user{:href => "https://www.mercari.com/jp/u/178529040/"}
                %figure
                  %div
                    %img{:alt => "", :src => "//static.mercdn.net/images/member_photo_noimage_thumb.png"}/
                  %figcaption.bold
                    メルカリタロウ
              .message-body
                .message-body-text こんにちは、よろしくお願いします！
                .message-icons.clearfix
                  %time.message-icon-left
                    %i.fa.fa-clock-o
                    %span 0 秒前
                %i.icon-balloon
        .message-content2
          %form.message-form{:action => "https://www.mercari.com/jp/transaction/message/m18251864076/", :method => "POST"}
            %input{:name => "__csrf_value", :type => "hidden", :value => "a50969b0ebdc51fb05cb19bc49a1e9db2011786b93ef65c6eb24ee21407267529e12152d425a4ff8c7423eab9d587880161901ad69b4c4d8c5c9808af854f5dd6"}/
            %p 取引メッセージの内容は、必要に応じて事務局で確認しています
            %input{:name => "item_id", :type => "hidden", :value => "m18251864076"}/
            %textarea.textarea-default{:name => "body", :type => "text", :value => ""}
            %button.message-submit.btn-default.btn-gray{:type => "submit"}
              %span 取引メッセージを送る
        %aside.modal{"data-close" => "modal", "data-modal" => "delete-comment"}
          .modal-inner.modal-banner
            .modal-body
              .modal-head.bold 確認
              %div{"data-comment" => "body"}
              %br/
              本当にこのコメントを削除してよろしいですか？
            %form{:action => "https://www.mercari.com/jp/comment/delete/", :method => "POST"}
              .clearfix
                .modal-btn.modal-btn-cancel{"data-close" => "modal"} キャンセル
                %button.modal-btn.modal-btn-submit{:type => "submit"}
                  削除する
              %input{:name => "item_id", :type => "hidden", :value => "m18251864076"}/
              %input{:name => "comment_id", :type => "hidden", :value => ""}/
              %input{:name => "__csrf_value", :type => "hidden", :value => "a50969b0ebdc51fb05cb19bc49a1e9db2011786b93ef65c6eb24ee21407267529e12152d425a4ff8c7423eab9d587880161901ad69b4c4d8c5c9808af854f5dd6"}/
      .message-content3
        ※お困りの際は
        %a{:href => "/jp/help_center/category/1/", :target => "_blank"}> よくある質問
        をご確認ください。
    %aside.modal{"data-close" => "modal", "data-modal" => "seller-cancel"}
      .modal-inner.modal-banner
        .modal-body
          .modal-head.bold 取引をキャンセルしますか？
          キャンセル後、商品は出品停止状態になりますので、再度出品をお願いいたします
        .clearfix
          .modal-btn.modal-btn-cancel{"data-close" => "modal"} いいえ
          %form{:action => "/jp/transaction/seller_cancel/done/m18251864076/", :method => "POST", :novalidate => "novalidate"}
            %input{:name => "__csrf_value", :type => "hidden", :value => "a50969b0ebdc51fb05cb19bc49a1e9db2011786b93ef65c6eb24ee21407267529e12152d425a4ff8c7423eab9d587880161901ad69b4c4d8c5c9808af854f5dd6"}/
            %button.modal-btn.modal-btn-submit{:type => "submit"} はい
    %aside.modal{"data-close" => "modal", "data-modal" => "buyer-cancel"}
      .modal-inner.modal-banner
        .modal-body
          .modal-head.bold 取引キャンセルを依頼しますか
          事務局にて取引内容を確認後、対応してまいります
        .clearfix
          .modal-btn.modal-btn-cancel{"data-close" => "modal"} キャンセル
          %form{:action => "/jp/transaction/buyer_cancel/done/m18251864076/", :method => "POST", :novalidate => "novalidate"}
            %input{:name => "__csrf_value", :type => "hidden", :value => "a50969b0ebdc51fb05cb19bc49a1e9db2011786b93ef65c6eb24ee21407267529e12152d425a4ff8c7423eab9d587880161901ad69b4c4d8c5c9808af854f5dd6"}/
            %button.modal-btn.modal-btn-submit{:type => "submit"} はい
  .l-side
    %section.l-side-container
      %h3.transact-info-head 取引情報
      .transact-info-inner
        %ul.transact-info-table
          %li.transact-info-table-row
            %span.transact-info-table-cell 商品
            %ul.transact-info-table-cell
              %li
                %a{:href => "https://item.mercari.com/jp/m18251864076/"}
                  %img.lazyloaded{:alt => "", "data-src" => "https://static.mercdn.net/thumb/photos/m46233963393_1.jpg?1552715495", :src => "https://static.mercdn.net/thumb/photos/m46233963393_1.jpg?1552715495"}/
                  .transact-info-item.bold
                    水筒
                    %br/
                    ¥ 500
          %li.transact-info-table-row
            %span.transact-info-table-cell 送料
            %ul.transact-info-table-cell
              %li
                送料込み(出品者負担)
          %li.transact-info-table-row
            %span.transact-info-table-cell 購入日時
            %ul.transact-info-table-cell
              %li 3月25日 14:14
          %li.transact-info-table-row
            %span.transact-info-table-cell 商品ID
            %ul.transact-info-table-cell
              %li m18251864076
          %li.transact-info-table-row
            %span.transact-info-table-cell お届け先
            %ul.transact-info-table-cell
              %li
                %p 〒451-0053
                %p
                  愛知県名古屋市中村区0-00-00
                %p
                  %span.buyer-name
                    メルカリ
                    タロウ
                  %span.sama
                    様
    %section.l-side-container
      %h3.transact-info-head 出品者情報
      .transact-info-inner
        %a.transaction-user-icon{:href => "#"}
          %figure
            %div.image-box
              %img{:alt => "", :src => "//static.mercdn.net/images/member_photo_noimage_thumb.png", :width => "40"}/
            %figcaption.bold
              .transact-user-name
                メルカリ二郎
          %i.fa.fa-angle-right



= render 'shared/footer'