config/routes.rb
Rails.application.routes.draw do

  root 'items#index'

  get 'likes/create'
  get 'likes/destroy'

  post 'users/card_create',   to: 'users#card_create'
  delete 'users/card_delete', to: 'users#card_delete'

  match 'category_select',       to: 'items#category_select',       via: [:get, :post]
  match 'child_category_select', to: 'items#child_category_select', via: [:get, :post]

  devise_for :users, controllers: {
    registrations:      'users/registrations',
    sessions:           'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get  'to_signup',      to: 'users/registrations#to_signup'
    post 'signup/profile', to: 'users/registrations#profile'
    post 'signup/address', to: 'users/registrations#address'
    post 'signup/credit',  to: 'users/registrations#credit'
  end

  resources :users,except: :show do
    get :logout,               on: :collection
    get :payment_method,       on: :collection
    get :card_registration,    on: :collection
    get :indentification,      on: :collection
    get :trading,              on: :collection
    get :purchased,            on: :collection
    get :exhibition,           on: :collection
    get :seller_trading,       on: :collection
    get :sold_page,            on: :collection
    get :notification,         on: :collection
    get :todo,                 on: :collection
    get :individual,           on: :member
    resources :likes,     only: :index
    resources :addresses, only: [:edit, :update]
    resources :lates,     only: :index do
      get :great,              on: :collection
      get :good,               on: :collection
      get :poor,               on: :collection
    end
    member do
     get :following, :followers
    end
  end

  scope :profiels do
    resources :users, only: :show
  end

  resources :items do
    get  :buy,                 on: :collection
    get  :all_categories_show, on: :collection
    get  :item_search_result,  on: :collection
    get  :buy,                 on: :member
    post :pay,                 on: :member
    get  :trading_message,     on: :member
    post :trading_page,        on: :member
    post :message,             on: :member
    post :late,                on: :member
    resources :comments, only: [:create, :destroy]
    resources :likes,    only: [:create, :destroy]
  end

  resources :categories, only: :show do
    get :child_category,       on: :collection
    get :grand_child_category, on: :collection
  end

  resources :brands, only: :show do
    get :brand_show,          on: :member
  end

  resources :relationships, only: [:create, :destroy]

end

app/views/shared/_buy-sell-items.html.haml
%main.l-container
  = render 'shared/l-side'
  .l-content
    %section.mypage-tab-container-bottom
      %h2.mypage-tab-container-bottom__head
        - url = request.path_info
        - if url.match('purchased') || (url.match('trading') && (not url.match('seller_trading')))
          購入した商品
        - else
          出品した商品

      %ul.mypage-tab-container__tabs
        = render 'shared/mypage-tabs'
      .tab-content
        %ul#mypage-tab-transaction-now.mypage-item-list.tab-pane.active
          - if @item.present?
            - @item.each do |item|
              %li.mypage-item-lists
                - if url.match('exhibition')
                  = link_to item_path(item.id),class: 'mypage-item-lists__link' do
                    %figure
                      = image_tag item.item_images.first.image
                    .mypage-item-lists__body
                      .mypage-item-lists__body--text
                        = item.name
                      .mypage-item-lists__status.awaiting
                        出品中
                    %i.fa.fa-angle-right.mypage-item-lists-icon
                - else
                  = link_to trading_message_item_path(item.id),class: 'mypage-item-lists__link' do
                    %figure
                      = image_tag item.item_images.first.image
                    .mypage-item-lists__body
                      .mypage-item-lists__body--text
                        - url = request.path_info
                        - if url.match('purchased')
                          = "「#{item.name}」を購入しました。取引が完了しました。"
                        - else
                          = item.name
                      - url = request.path_info
                      - if url.match('purchased')
                        .mypage-item-lists__status.done
                          取引完了
                      - if url.match('sold_page')
                        .mypage-item-lists__status.done
                          売却済
                      - if item.business_stats == 2 && item.delivery_status == 0
                        .mypage-item-lists__status.trading
                          発送待ち
                      - if item.business_stats == 2 && item.delivery_status == 1
                        .mypage-item-lists__status.trading
                          受取評価待ち
                      - if item.business_stats == 2 && item.delivery_status == 2
                        .mypage-item-lists__status.trading
                          出品者評価待ち
                    %i.fa.fa-angle-right.mypage-item-lists-icon

          - else
            %li.mypage-item-not-found.bold
              - url = request.path_info
              - if url.match('trading')
                取引中の商品がありません
              - if url.match('purchased')
                購入済みの商品がありません
              - if url.match('exhibition')
                出品中の商品がありません
              - if url.match('sold_page')
                売却済みの商品がありません

app/views/shared/_category-drop-menu.html.haml
/ メインカテゴリーul
%ul.main-category.hidden
  - @category.each do |category|
    %li.main-category__list{id: "category_id_#{category.id}"}
      = link_to category_path(category.id),class: "lists-menu__categories--category-link" do
        %h3.main-category__name
          = category.name
        / 子カテゴリーul
        %ul.child-category.hidden{id: "child_category_ul_#{category.id}"}
          - @child_category[category.id - 1].each do |child_category|
            %li.child-category__list{id: "child_category_li_#{child_category.id}"}
              = link_to category_path(child_category.id),class: "child-category__sub-category-link" do
                = child_category.name
              / 孫カテゴリーul
              %ul.child-category.hidden{id: "grand_child_category_ul_#{child_category.id}"}
                - grand_child_category = Category.where(main_category_id: category.id).where(sub_category_id: child_category.id)
                - grand_child_category.each_with_index do |grand_child_category, i|
                  %li.child-category__list.grand-child-list-width
                    = link_to category_path(grand_child_category.id),class: "child-category__sub-category-link" do
                      = grand_child_category.name
                  - break if i == 19

  %li.main-category__list
    = link_to all_categories_show_items_path,class: "lists-menu__categories--category-link" do
      %h3.main-category__name
        カテゴリー一覧

app/views/shared/_errors_messages.html.haml
%ul.errors
  - temporary.errors.full_messages.each do |message|
    %li
      = message

app/views/shared/_footer.html.haml
%aside.footer-app-bar
  = image_tag("/images/mercari-sample.jpg", class: "footer-app-bar__image")

%footer.footer
  %nav.footer__nav
    %ul.footer-container
      %li.footer-menu
        %h2.footer-menu__title
          メルカリについて
        %ul
          %li.footer-menu__list
            = link_to "会社概要（運営会社）","https://about.mercari.com/"
          %li.footer-menu__list
            = link_to "プライバシーポリシー","https://www.mercari.com/jp/privacy/"
          %li.footer-menu__list
            = link_to "メルカリ利用規約","https://www.mercari.com/jp/tos/"
          %li.footer-menu__list
            = link_to "有償ポイントに関する特約","https://www.mercari.com/jp/tos_paid_point/"
          %li.footer-menu__list
            = link_to "あんしんスマホサポート制度に関する利用特約","https://www.mercari.com/jp/tos_smartphone_support/"
          %li.footer-menu__list
            = link_to "コンプライアンスポリシー","https://www.mercari.com/jp/compliance/"
          %li.footer-menu__list
            = link_to "個人データの安全管理に係る基本方針","https://www.mercari.com/jp/data_security/"
          %li.footer-menu__list
            = link_to "特定商取引に関する表記","https://www.mercari.com/jp/tokutei/"
          %li.footer-menu__list
            = link_to "資金決済法に基づく表示","https://www.mercari.com/jp/shikin_kessai/"
          %li.footer-menu__list
            = link_to "法令順守と犯罪抑止のために","https://about.mercari.com/csr/safety/"
          %li.footer-menu__list
            = link_to "採用情報","https://www.mercari.com/jp/jobs/"
      %li.footer-menu
        %h2.footer-menu__title
          メルカリを見る
        %ul
          %li.footer-menu__list
            = link_to "カテゴリー一覧",all_categories_show_items_path
          %li.footer-menu__list
            = link_to "ブランド一覧",brand_path(1)
          %li.footer-menu__list
            = link_to "出品地域一覧","https://www.mercari.com/jp/area/"
          %li.footer-menu__list
            = link_to "公式ブログ","https://jp-news.mercari.com/", target: "_blank"
          %li.footer-menu__list
            = link_to "公式Twitter","https://twitter.com/mercari_jp", target: "_blank"
          %li.footer-menu__list
            = link_to "公式Facebook","https://www.facebook.com/mercarijp", target: "_blank"
      %li.footer-menu
        %h2.footer-menu__title
          ヘルプ＆ガイド
        %ul
          %li.footer-menu__list
            = link_to "メルカリガイド","https://www.mercari.com/jp/help_center/"
          %li.footer-menu__list
            = link_to "メルカリロゴ利用ガイドライン","https://www.mercari.com/jp/logo-guidelines/"
          %li.footer-menu__list
            = link_to "お知らせ","https://about.mercari.com/press/news/"
          %li.footer-menu__list
            = link_to "らくらくメルカリ便とは","https://www.mercari.com/jp/rakuraku-mercari/"
          %li.footer-menu__list
            = link_to "ゆうゆうメルカリ便とは","https://www.mercari.com/jp/yuyu-mercari/"
          %li.footer-menu__list
            = link_to "大型らくらくメルカリ便とは","https://www.mercari.com/jp/rakuraku-ogata/"
          %li.footer-menu__list
            = link_to "車体取引ガイド","https://www.mercari.com/jp/guide/car/"
          %li.footer-menu__list
            = link_to "返品・返金ポリシー","https://www.mercari.com/jp/refund-returns/"
          %li.footer-menu__list
            = link_to "メルカリあんしん・あんぜん宣言！","https://www.mercari.com/jp/safe/description/", target: "_blank"
          %li.footer-menu__list
            = link_to "偽ブランド品撲滅への取り組み","https://www.mercari.com/jp/authenticity/"
          %li.footer-menu__list
            = link_to "メルカリボックス","https://www.mercari.com/jp/box/"
      %li.footer-menu
        %h2.footer-menu__title
          国
        %ul
          %li.footer-menu__list
            = link_to "https://www.mercari.com/", class: "lang-menu-non-active" do
              = image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/flag_us.png?2845599746", alt: "lang-us",class: "lang-menu-icon")
              United States
          %li.footer-menu__list
            = link_to "https://www.mercari.com/uk/", class: "lang-menu-non-active" do
              = image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/flag_uk.png?2845599746", alt: "lang-uk",class: "lang-menu-icon")
              United Kingdom
          %li.footer-menu__list
            = link_to "https://www.mercari.com/jp/", class: "lang-menu-active" do
              = image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/flag_jp.png?2845599746", alt: "lang-ja",class: "lang-menu-icon")
              日本

  = link_to "https://www.mercari.com/jp/", class: "footer__logo" do
    = image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?2845599746", alt: "mercari-logo",class: "footer__logo--image")
  %p.footer__copyright
    %small
      &copy; 2019 Mercari

app/views/shared/_header.html.haml
.default-container{id: 0}
  %header
    .logo-and-search
      =link_to root_path do
        = image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?2845599746", class: "logo-and-search__logo left-float")
      = search_form_for @search, url: item_search_result_items_path,class: "logo-and-search__search right-float" do |f|
        = f.search_field :name_cont ,placeholder: "キーワードから探す", value: "#{params[:q]["name_cont"] if params[:q]}", class: "logo-and-search__form"
        = button_tag type: "submit", class: "logo-and-search__icon" do
          %i.fa.fa-search
    .header-lists
      .header-lists__left.left-float
        %ul.lists-menu
          %li.lists-menu__categories
            %h2.lists-menu__text.category-nav
              = link_to "カテゴリーから探す", all_categories_show_items_path,class: "lists-menu__link"
            = render "shared/category-drop-menu"

          %li.lists-menu__brands
            %h2.lists-menu__text.brand-nav
              = link_to "ブランドから探す", brand_path(1),class: "lists-menu__link"
            = render "shared/brand-drop-menu"

      .header-lists__right.right-float
        - if user_signed_in?
          %ul.pc-header-nav
            %li
              = link_to users_path(current_user), class: "pc-header-nav__user-icon pc-header-nav__root" do
                %figure
                  - if current_user.persisted? && current_user.avatar?
                    = image_tag current_user.avatar.to_s, class: 'avatar_present_img'
                  - else
                    = image_tag "//static.mercdn.net/images/member_photo_noimage_thumb.png", alt: ""
                %div マイページ
              = render 'shared/mypage_drop_down'

            %li
              = link_to '#', class: "pc-header-nav__root",'data-url':'https://www.mercari.com/jp/mypage/notification_and_todo_json/' do
                %i.fa.fa-bell.icon
                %span お知らせ
                .pc-header-nav__root__count
                  5

            %li
              = link_to '#',class: 'pc-header-nav__root','data-url':'https://www.mercari.com/jp/mypage/notification_and_todo_json/' do
                %i.fa.fa-check
                %span やることリスト

        - else
          %ul.signin-signup
            %li.signin-btn
              = link_to "ログイン",new_user_session_path ,class: "signin-btn__text"
            %li.signup-btn
              = link_to "新規会員登録",to_signup_path ,class: "signup-btn__text"

  %nav.nav-var
    = breadcrumbs separator: " #{content_tag(:i, '', :class=>'fa fa-angle-right')} "

app/views/shared/_l-side.html.haml
.l-side.clearfix
  %nav.mypage-nav
    %ul.mypage-nav__list
      %li
        = link_to users_path(current_user),class: "mypage-nav__list__item" do
          マイページ
          = fa_icon 'angle-right', class: 'mypage-icon'
      %li
        = link_to notification_users_path,class: "mypage-nav__list__item" do
          お知らせ
          %span.mypage-nav-number
            5
          = fa_icon 'angle-right', class: 'mypage-icon'
      %li
        = link_to todo_users_path,class: "mypage-nav__list__item" do
          やることリスト
          = fa_icon 'angle-right', class: 'mypage-icon'
      %li
        = link_to user_likes_path(current_user),class: "mypage-nav__list__item" do
          いいね！一覧
          = fa_icon 'angle-right', class: 'mypage-icon'
      %li
        = link_to new_item_path,class: "mypage-nav__list__item" do
          出品する
          = fa_icon 'angle-right', class: 'mypage-icon'
      %li
        = link_to exhibition_users_path(current_user),class: "mypage-nav__list__item" do
          出品した商品 - 出品中
          = fa_icon 'angle-right', class: 'mypage-icon'
      %li
        = link_to seller_trading_users_path(current_user),class: "mypage-nav__list__item" do
          出品した商品 - 取引中
          = fa_icon 'angle-right', class: 'mypage-icon'
      %li
        = link_to sold_page_users_path(current_user),class: "mypage-nav__list__item" do
          出品した商品 - 売却済み
          = fa_icon 'angle-right', class: 'mypage-icon'
      %li
        = link_to trading_users_path(current_user),class: "mypage-nav__list__item" do
          購入した商品 - 取引中
          = fa_icon 'angle-right', class: 'mypage-icon'
      %li
        = link_to purchased_users_path(current_user),class: "mypage-nav__list__item" do
          購入した商品 - 過去の取引
          = fa_icon 'angle-right', class: 'mypage-icon'
      %li
        = link_to '#',class: "mypage-nav__list__item" do
          ニュース一覧
          = fa_icon 'angle-right', class: 'mypage-icon'
      %li
        = link_to user_lates_path(current_user),class: "mypage-nav__list__item" do
          評価一覧
          = fa_icon 'angle-right', class: 'mypage-icon'
      %li
        = link_to '#',class: "mypage-nav__list__item" do
          ガイド
          = fa_icon 'angle-right', class: 'mypage-icon'
      %li
        = link_to '#',class: "mypage-nav__list__item" do
          お問い合わせ
          = fa_icon 'angle-right', class: 'mypage-icon'
    %h3.mypage-nav__head メルペイ
    %ul.mypage-nav__list--margin-top
      %li
        = link_to '#',class: "mypage-nav__list__item" do
          売上・振込申請
          = fa_icon 'angle-right', class: 'mypage-icon'
      %li
        = link_to '#',class: "mypage-nav__list__item" do
          ポイント
          = fa_icon 'angle-right', class: 'mypage-icon'
    %h3.mypage-nav__head 設定
    %ul.mypage-nav__list--margin-top
      %li
        = link_to "/profiels#{user_path(current_user)}",class: "mypage-nav__list__item" do
          プロフィール
          = fa_icon 'angle-right', class: 'mypage-icon'
      %li
        = link_to edit_user_address_path(current_user,current_user&.address),class: "mypage-nav__list__item" do
          発送元・お届け先住所変更
          = fa_icon 'angle-right', class: 'mypage-icon'
      %li
        = link_to payment_method_users_path(current_user),class: "mypage-nav__list__item" do
          支払い方法
          = fa_icon 'angle-right', class: 'mypage-icon'
      %li
        = link_to edit_user_registration_path,class: "mypage-nav__list__item" do
          メール/パスワード
          = fa_icon 'angle-right', class: 'mypage-icon'
      %li
        = link_to indentification_users_path(current_user),class: "mypage-nav__list__item" do
          本人情報
          = fa_icon 'angle-right', class: 'mypage-icon'
      %li
        = link_to '#',class: "mypage-nav__list__item" do
          電話番号の確認
          = fa_icon 'angle-right', class: 'mypage-icon'
      %li
        = link_to logout_users_path,class: "mypage-nav__list__item" do
          ログアウト
          = fa_icon 'angle-right', class: 'mypage-icon'

app/views/shared/_like.html.haml
- if user_signed_in? && item.user_id != current_user.id
  - unless item.like_user(current_user.id).blank?
    = link_to item_like_path(item_id: item.id ,id: item.likes[0].id), method: :delete, remote: true, url: url_for(action: :destroy) do
      .vertical-like.red-text
        %i.fa.fa-heart.vertical-like__red-icon  いいね!
        %span.vertical-like__red-text
          - if item.likes_count != 0
            = item.likes_count
  - else
    = link_to item_likes_path(item.id), method: :post, remote: true, url: url_for(action: :create) do
      .vertical-like
        %i.fa.fa-heart.vertical-like__icon  いいね!
        %span.vertical-like__text
          - if item.likes_count != 0
            = item.likes_count
- else
  .vertical-like
    %i.fa.fa-heart.vertical-like__icon  いいね!
    %span.vertical-like__text
      - if item.likes_count != 0
        = item.likes_count

app/views/shared/_messages.html.haml
- messages.each do |message|
  %ul.message-items
    - if message.user_id != current_user.id
      %li.message-left
        %a.message-user{:href => ""}
          %figure
            %div
              - if message.user.persisted? && message.user.avatar?
                = image_tag message.user.avatar.to_s, class: 'avatar_present_img'
              - else
                = image_tag "//static.mercdn.net/images/member_photo_noimage_thumb.png", alt: ""
            %figcaption.bold
              = message.user.nickname
        .message-body
          .message-body-text
            = message.text
          .message-icons.clearfix
            %time.message-icon-left
              %i.fa.fa-clock-o
              %span
                = time_ago_in_words(message.created_at)+"前"
          %i.fa.fa-caret-down

    - elsif message.user_id == current_user.id
      %li.message-right
        %a.message-user{:href => ""}
          %figure
            %div
              - if message.user.persisted? && message.user.avatar?
                = image_tag message.user.avatar.to_s, class: 'avatar_present_img'
              - else
                = image_tag "//static.mercdn.net/images/member_photo_noimage_thumb.png", alt: ""
            %figcaption.bold
              = current_user.nickname
        .message-body
          .message-body-text
            = message.text
          .message-icons.clearfix
            %time.message-icon-left
              %i.fa.fa-clock-o
              %span
                = time_ago_in_words(message.created_at)+"前"
          %i.fa.fa-caret-down

app/views/shared/_mypage-tabs.html.haml
- url = request.path_info
- if url.match('purchased')
  %li.two-tabs
    %h3
      = link_to '取引中',trading_users_path(current_user),id: 'mypage-tab-transaction-now','data-toggle':'tab'
  %li.two-tabs.active
    %h3
      = link_to '過去の取引',purchased_users_path(current_user),id: 'mypage-tab-transaction-old','data-toggle':'tab'

- if url.match('trading') && (not url.match('seller_trading'))
  %li.two-tabs.active
    %h3
      = link_to '取引中',trading_users_path(current_user),id: 'mypage-tab-transaction-now','data-toggle':'tab'
  %li.two-tabs
    %h3
      = link_to '過去の取引',purchased_users_path(current_user),id: 'mypage-tab-transaction-old','data-toggle':'tab'

- if url.match('sold_page')
  %li.three-tabs
    %h3
      = link_to '出品中',exhibition_users_path(current_user),id: 'mypage-tab-transaction-now','data-toggle':'tab'
  %li.three-tabs
    %h3
      = link_to '取引中',seller_trading_users_path(current_user),id: 'mypage-tab-transaction-now','data-toggle':'tab'
  %li.three-tabs.active
    %h3
      = link_to '売却済み',sold_page_users_path(current_user),id: 'mypage-tab-transaction-old','data-toggle':'tab'

- if url.match('exhibition')
  %li.three-tabs.active
    %h3
      = link_to '出品中',exhibition_users_path(current_user),id: 'mypage-tab-transaction-now','data-toggle':'tab'
  %li.three-tabs
    %h3
      = link_to '取引中',seller_trading_users_path(current_user),id: 'mypage-tab-transaction-now','data-toggle':'tab'
  %li.three-tabs
    %h3
      = link_to '売却済み',sold_page_users_path(current_user),id: 'mypage-tab-transaction-old','data-toggle':'tab'

- if url.match('seller_trading')
  %li.three-tabs
    %h3
      = link_to '出品中',exhibition_users_path(current_user),id: 'mypage-tab-transaction-now','data-toggle':'tab'
  %li.three-tabs.active
    %h3
      = link_to '取引中',seller_trading_users_path(current_user),id: 'mypage-tab-transaction-now','data-toggle':'tab'
  %li.three-tabs
    %h3
      = link_to '売却済み',sold_page_users_path(current_user),id: 'mypage-tab-transaction-old','data-toggle':'tab'

- if url.match('lates')
  %li.four-tabs.all
    %h3
      = link_to 'すべて',user_lates_path(current_user),id: 'mypage-tab-transaction-now','data-toggle':'tab'
  %li.four-tabs.good
    %i.fa.fa-grin.icon-good
    %h3
      = link_to '良い',great_user_lates_path(current_user),id: 'mypage-tab-transaction-now','data-toggle':'tab'
  %li.four-tabs.normal
    %i.fa.fa-meh.icon-normal
    %h3
      = link_to '普通',good_user_lates_path(current_user),id: 'mypage-tab-transaction-old','data-toggle':'tab'
  %li.four-tabs.bad
    %i.fa.fa-frown.icon-bad
    %h3
      = link_to '悪い',poor_user_lates_path(current_user),id: 'mypage-tab-transaction-old','data-toggle':'tab'

app/views/shared/_mypage_drop_down.html.haml
.header-mypage-box
  .header-mypage-box__state
    %figure.header-mypage-box__state__figure
      .header-mypage-box__state__figure__div
        - if current_user.persisted? && current_user.avatar?
          = image_tag current_user.avatar.to_s, class: 'avatar_present_img'
        - else
          = image_tag "//static.mercdn.net/images/member_photo_noimage_thumb.png", alt: ""
      %figcaption
        = current_user&.nickname

    %ul.header-mypage-box__state__listing
      %li.header-mypage-box__state__listing__li
        = link_to user_lates_path(current_user) do
          評価: #{current_user&.late_count}
      %li.header-mypage-box__state__listing__li
        = link_to exhibition_users_path(current_user) do
          出品数: #{current_user&.items&.count}

    %ul.header-mypage-box__state__points
      %li.header-mypage-box__state__points__li
        = link_to '#', class: "clearfix" do
          .left 売上金
          .right
            = "¥ #{thousands_separator(@total_price)}"
            = fa_icon 'angle-right',class: 'mypage-nav-icon'

      %li.header-mypage-box__state__points__li
        = link_to '#',class: "clearfix" do
          .left ポイント
          .right
            P 0
            = fa_icon 'angle-right',class: 'mypage-nav-icon'

  %ul.header-mypage-box__list
    %li
      = link_to user_likes_path(current_user),class: "link-item" do
        いいね！一覧

        = fa_icon 'angle-right',class: 'mypage-nav-icon'
    %li
      = link_to exhibition_users_path(current_user),class: "link-item" do
        出品した商品 - 出品中
        = fa_icon 'angle-right',class: 'mypage-nav-icon'
    %li
      = link_to seller_trading_users_path(current_user),class: "link-item" do
        出品した商品 - 取引中
        = fa_icon 'angle-right',class: 'mypage-nav-icon'
    %li
      = link_to sold_page_users_path(current_user),class: "link-item" do
        出品した商品 - 売却済み
        = fa_icon 'angle-right',class: 'mypage-nav-icon'
    %li
      = link_to trading_users_path(current_user),class: "link-item" do
        購入した商品 - 取引中
        = fa_icon 'angle-right',class: 'mypage-nav-icon'
    %li
      = link_to purchased_users_path(current_user),class: "link-item" do
        購入した商品 - 過去の取引
        = fa_icon 'angle-right',class: 'mypage-nav-icon'

app/views/shared/_search_right.html.haml
.search-container__right-contents
  .hidden-large.search-nav

  %section.items-boxes
    %h3.items-boxes__result
      - if @search_items.nil?
        検索結果 0 件
      - else
        = "検索結果 1-#{@search_items.length} 件"
    .items-boxes__lists
      - @search_items.each do |item|
        %section.items-card
          = link_to item_path(item), class: "item-link" do
            %figure.items-card__photo
              = image_tag item.item_images.first.image
            - if item.business_stats == 3
              .items-card__sold-out
                %div SOLD
            .items-card-intro
              %h3.items-card-intro__item-name
                = item.name
              .items-card-num
                .items-card-num__price
                  = "¥ #{thousands_separator(item.price)}"
                - if item.likes_count != 0
                  .items-card-num__likes
                    %i.fa.fa-heart
                    %span
                      = item.likes_count
              %p.items-card-intro__tax
                (税込)
  = paginate @search_items

app/views/shared/_todo_header.html.haml
%ul.mypage-tab-container__tabs
  - url = request.path_info
  - if url.match(notification_users_path)
    %li.two-tabs.active
      %h3
        = link_to notification_users_path,id: "mypage-tab-notification",'data-toggle':'tab' do
          お知らせ

    %li.two-tabs
      %h3
        = link_to todo_users_path,id: "mypage-tab-todo",'data-toggle':'tab' do
          やることリスト

  - if url.match(todo_users_path)
    %li.two-tabs
      %h3
        = link_to notification_users_path,id: "mypage-tab-notification",'data-toggle':'tab' do
          お知らせ

    %li.two-tabs.active
      %h3
        = link_to todo_users_path,id: "mypage-tab-todo",'data-toggle':'tab' do
          やることリスト

app/views/shared/_toppage_category_items.html.haml
%section.items-boxes
  %h3.items-boxes__category.text-center
    = link_to "#{category.name} 新着アイテム",category_path(category.id), class: "new-item"
  .items-boxes__lists
    - item.each do |item|
      %section.items-card
        = link_to item_path(item), class: "item-link" do
          %figure.items-card__photo
            = image_tag item.item_images.first.image
          - if item.business_stats == 3
            .items-card__sold-out
              %div SOLD
          .items-card-intro
            %h3.items-card-intro__item-name
              = item.name
            .items-card-num
              .items-card-num__price
                = "¥ #{thousands_separator(item.price)}"
              - if item.likes_count != 0
                .items-card-num__likes
                  %i.fa.fa-heart
                  %span
                    = item.likes_count
            %p.items-card-intro__tax
              (税込)
  .items-boxes__view-all.l-right
    = link_to "すべての商品を見る",category_path(category.id)

app/views/shared/_unique_error.html.haml
%ul.errors
  - errors.each do |message|
    %li
      = message