config/routes.rb
Rails.application.routes.draw do

  root 'items#index'

  get 'likes/create'
  get 'likes/destroy'

  post 'users/card_create',   to: 'users#card_create'
  delete 'users/card_delete', to: 'users#card_delete'

  match 'category_select',       to: 'items#category_select',       via: [:get, :post]
  match 'child_category_select', to: 'items#child_category_select', via: [:get, :post]

  devise_for :users, controllers: {
    registrations:      'users/registrations',
    sessions:           'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get  'to_signup',      to: 'users/registrations#to_signup'
    post 'signup/profile', to: 'users/registrations#profile'
    post 'signup/address', to: 'users/registrations#address'
    post 'signup/credit',  to: 'users/registrations#credit'
  end

  resources :users,except: :show do
    get :logout,               on: :collection
    get :payment_method,       on: :collection
    get :card_registration,    on: :collection
    get :indentification,      on: :collection
    get :trading,              on: :collection
    get :purchased,            on: :collection
    get :exhibition,           on: :collection
    get :seller_trading,       on: :collection
    get :sold_page,            on: :collection
    get :notification,         on: :collection
    get :todo,                 on: :collection
    get :individual,           on: :member
    resources :likes,     only: :index
    resources :addresses, only: [:edit, :update]
    resources :lates,     only: :index do
      get :great,              on: :collection
      get :good,               on: :collection
      get :poor,               on: :collection
    end
    member do
     get :following, :followers
    end
  end

  scope :profiels do
    resources :users, only: :show
  end

  resources :items do
    get  :buy,                 on: :collection
    get  :all_categories_show, on: :collection
    get  :item_search_result,  on: :collection
    get  :buy,                 on: :member
    post :pay,                 on: :member
    get  :trading_message,     on: :member
    post :trading_page,        on: :member
    post :message,             on: :member
    post :late,                on: :member
    resources :comments, only: [:create, :destroy]
    resources :likes,    only: [:create, :destroy]
  end

  resources :categories, only: :show do
    get :child_category,       on: :collection
    get :grand_child_category, on: :collection
  end

  resources :brands, only: :show do
    get :brand_show,          on: :member
  end

  resources :relationships, only: [:create, :destroy]

end

app/models/item.rb
class Item < ApplicationRecord

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :result_order
  belongs_to_active_hash :size
  belongs_to_active_hash :price_search
  belongs_to_active_hash :item_status
  belongs_to_active_hash :business_status
  belongs_to_active_hash :shipping_method

  has_many :item_images,dependent: :delete_all
  accepts_nested_attributes_for :item_images, allow_destroy: true
  has_many :likes, dependent: :destroy
  has_many :comments,dependent: :delete_all
  has_many :messages,dependent: :delete_all
  belongs_to :user
  belongs_to :category
  belongs_to :brand,optional: true
  has_one    :late

  with_options presence: true do
    validates :name,        length: { maximum: 40 }
    validates :explain,     length: { maximum: 1000 }
    validates :state
    validates :shipping_date
    validates :postage
    validates :shipping_way
    validates :category_id
    validates :child_category_id
    validates :price,        numericality: { only_integr: true,greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }
  end

  def like_user(user_id)
   likes.find_by(user_id: user_id)
  end

  ransacker :created_at do
    Arel::Nodes::SqlLiteral.new "date(items.created_at)"
  end

  enum state: {
    '新品、未使用': 1,
    '未使用に近い': 2,
    '目立った傷や汚れなし': 3,
    'やや傷や汚れあり': 4,
    '傷や汚れあり': 5,
    '全体的に状態が悪い': 6
  }

  enum shipping_date: {
    "1~2日で発送": 1,
    "2~3日で発送": 2,
    "4~7日で発送": 3
  }

  enum postage: {
    "送料込み(出品者負担)": 1,
    "着払い(購入者負担)": 2
  }

  enum shipping_way: {
    "未定": 1,
    "クロネコヤマト": 2,
    "ゆうパック": 3,
    "ゆうメール": 4
  }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  require 'payjp'

  before_action :authenticate_user! ,   only: [:new ,:buy, :pay]
  before_action :address_create,        only: [:buy, :pay]
  before_action :set_category,          only: [ :index, :new, :edit, :create, :update, :all_brands_show, :all_categories_show, :show, :item_search_result, :trading_message]
  before_action :set_item,              only: [:show ,:edit, :update, :destroy, :buy, :message]
  before_action :set_payjp_user ,       only: [:buy, :pay]
  before_action :set_search
  before_action :set_searches ,         only: [:item_search_result]
  before_action :category_in_brand ,    only: [:all_brands_show]
  before_action :set_user,              only: [:index,:show]
  before_action :get_category,          only: [:show, :edit]
  before_action :set_price,             only: [:index, :new, :edit, :create, :update, :all_brands_show, :all_categories_show, :show, :item_search_result, :trading_message]
  before_action :set_late_count ,       only: :show

  def index
    @lady_items = Item.where(category_id: 1).where.not(business_stats: 2).limit(4).order(id: "DESC")
    @man_items = Item.where(category_id: 2).where.not(business_stats: 2).limit(4).order(id: "DESC")
    @kids_items = Item.where(category_id: 3).where.not(business_stats: 2).limit(4).order(id: "DESC")
    @cosmetic_items = Item.where(category_id: 6).where.not(business_stats: 2).limit(4).order(id: "DESC")
    @chanel_items = Item.where(brand_id: 2447).where.not(business_stats: 2).limit(4).order(id: "DESC")
    @nike_items = Item.where(brand_id: 3813).where.not(business_stats: 2).limit(4).order(id: "DESC")
    @vuitton_items = Item.where(brand_id: 6155).where.not(business_stats: 2).limit(4).order(id: "DESC")
    @supreme_items = Item.where(brand_id: 8413).where.not(business_stats: 2).limit(4).order(id: "DESC")

    @chanel = 'シャネル'
    @nike = 'ナイキ'
    @vuitton = 'ルイ ヴィトン'
    @supreme = 'シュプリーム'

    @category_name = []
    @category_name << Category.find(1)
    @category_name << Category.find(2)
    @category_name << Category.find(3)
    @category_name << Category.find(6)

    @category_items = [ @lady_items, @man_items, @kids_items, @cosmetic_items]
    @brand_items = [ @chanel_items, @nike_items, @vuitton_items, @supreme_items]
    @brand_names = [ @chanel, @nike, @vuitton, @supreme]
  end

  def new
    @item = Item.new
    30.times {@item.item_images.build}
    @brands = Brand.where('name LIKE(?)', "%#{params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @item = Item.new(item_params)
    brand_id = Brand.find_by(name: params[:item][:brand_id])
    @item.brand_id = brand_id.id if brand_id.present?
    if @item.save
      redirect_to root_path
    else
      check_item_name(@item.name)
      check_price(@item.price)
      check_explain(@item.explain)
      check_image(@item.item_images)
      check_category(@item.category_id,@item.child_category_id)
      check_state(@item.state)
      check_region(@item.region)
      check_postage(@item.postage)
      check_date(@item.shipping_date)
      check_way(@item.shipping_way)
      t = 30 - @item.item_images.length
      t.times {@item.item_images.build}
      @item.valid?
      render new_item_path
    end
  end

  def show
    @region = Prefecture.find(@item.region)
    @user_items = Item.where(user_id: @item.user.id).where.not(id: params[:id]).limit(6)
    @comment = Comment.new
    @comments = @item.comments
    if @grand_category == nil
      @child_category_items = Item.where(child_category_id: @children_category.id).where.not(user_id: @item.user.id).all
    else
      @grand_category_items = Item.where(grand_child_category_id: @grand_category.id).where.not(user_id: @item.user.id).all
    end
  end

  def edit
    20.times{@item.item_images.build}
    @child_category = Category.where.not(main_category_id: nil).where(sub_category_id: nil)
    @grand_child_category = Category.where.not(main_category_id: nil).where.not(sub_category_id: nil)
  end

  def update
    if @item.update(update_params)
      redirect_to item_path(@item)
    else
      check_item_name(@item.name)
      check_price(@item.price)
      check_image(@item.item_images)
      check_explain(@item.explain)
      check_category(@item.category_id,@item.child_category_id)
      check_state(@item.state)
      check_region(@item.region)
      check_postage(@item.postage)
      check_date(@item.shipping_date)
      check_way(@item.shipping_way)
      t = 20 - @item.item_images.length
      t.times {@item.item_images.build}
      @child_category = Category.where.not(main_category_id: nil).where(sub_category_id: nil)
      @grand_child_category = Category.where.not(main_category_id: nil).where.not(sub_category_id: nil)
      render :edit
    end
  end

  def destroy
    if @item.user_id == current_user.id
      @item.destroy
      redirect_to users_path
    else
      render :show,notice: '削除出来ませんでした'
    end
  end

  def item_search_result
    @category2 = Category.where.not(main_category_id: nil).where(sub_category_id: nil)
    @category3 = Category.where.not(main_category_id: nil).where.not(sub_category_id: nil)
    @brands = Brand.where('name LIKE(?)', "%#{params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def buy
    if @user.customer_id
      customer = Payjp::Customer.retrieve(@user.customer_id)
      @card = customer.cards.retrieve(customer.default_card)
    else
      redirect_to payment_method_users_path
    end
    @images = @item.item_images
    @region = Prefecture.find(@item.region)
  end

  def all_categories_show
  end

  def category_select
    @child_category = Category.where(main_category_id: params[:item][:category_id]).where(sub_category_id: nil)
  end

  def child_category_select
    child_category = Category.find(params[:item][:child_category_id])
    @grand_child_category = Category.where(main_category_id: child_category.main_category_id).where(sub_category_id: child_category.id)
  end

  def pay
    @item = Item.find(params[:id])
    @buyer = User.find(@item.buyer_id)
    if @user.customer_id == nil
      redirect_to payment_method_users_path
    else
      @charge = Payjp::Charge.create(
        :amount => @item.price,
        :customer => @user.customer_id,
        :currency => 'jpy',
      )
      @item.delivery_status = '3'
      @item.business_stats = '3'
      @late = Late.new(late_params)
      @late.user_id = @item.user_id
      @late.late_user = @item.buyer_id
      @buyer.late_count += 1
      @buyer.save(validate: false)
      @late.save(validate: false)
      if @item.save(validate: false)
        redirect_to trading_message_item_path, notice: '購入しました'
      else
        render :buy, notice: '購入出来ませんでした'
      end
    end
  end

  def trading_message
    @item = Item.find(params[:id])
    @user = User.find(current_user)
    @buyer = User.find(@item.buyer_id)
    @address = Address.find_by(user_id: @item.buyer_id)
    @prefecture = Prefecture.find(@address.prefecture_id)
    @message = Message.new
    @messages = Message.where(item_id: @item.id)
    @late = Late.new
  end

  def trading_page
    @item = Item.find(params[:id])
    @seller = User.find(@item.user_id)
    if @item.delivery_status == 1
      @late = Late.new(late_params)
      @late.user_id = @item.buyer_id
      @late.late_user = @item.user_id
      @seller.late_count += 1
      @seller.save(validate: false)
      @late.save(validate: false)
    end
    if @item.business_stats == 1
      @item.buyer_id = current_user.id
      @item.business_stats = 2
      @item.save(validate: false)
    else
      @item.delivery_status += 1
      @item.save(validate: false)
    end
    redirect_to trading_message_item_path
  end

  def message
    @message = Message.new(message_params)
    @message.save
    redirect_to trading_message_item_path
  end

  def address_create
    redirect_to edit_user_address_path(current_user,current_user&.address) if current_user.address.town.nil?
  end

  private
  def item_params
    params.require(:item).permit( :name, :price, :explain, :postage, :region, :state, :shipping_date, :shipping_way,:size, :brand_id, :category_id, :child_category_id, :grand_child_category_id, item_images_attributes: [:image]).merge(user_id: current_user.id, business_stats: '1')
  end

  def update_params
    params.require(:item).permit( :name, :price, :explain, :postage, :region, :state, :shipping_date, :shipping_way,:size,:brand_id, :category_id, :child_category_id, :grand_child_category_id, item_images_attributes: [:id,:image,:_destroy]).merge(user_id: current_user.id)
  end

  def pay_item_params
    params.permit(:item_id)
  end

  def message_params
    params.require(:message).permit(:text).merge(user_id: current_user.id, item_id: params[:id])
  end

  def late_params
    params.require(:late).permit(:text, :late)
  end

  def get_category
    @parent_category,@children_category,@grand_category = Category.find(@item.category_id,@item.child_category_id,@item.grand_child_category_id)
  end

  def set_item
    @item = Item.includes([:user,:item_images,:likes]).find(params[:id])
  end

  def set_user
    @user = User.includes(:items).find(current_user) if user_signed_in?
  end

  def set_payjp_user
    redirect_to new_user_session_path unless current_user
    @user = User.find(current_user)
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
  end

  def check_item_name(name)
    flash[:name] = "名前入力してください" if name.blank?
    flash[:name] = "40 文字以下で入力してください" if name.length > 40
  end

  def check_image(image)
    flash[:image] = "画像がありません" if image == []
  end

  def check_explain(explain)
    flash[:explain] = "説明入力してください" if explain.blank?
    flash[:explain] = "1000文字以下で入力してください" if explain.length > 1000
  end

  def check_price(price)
    flash[:price] = "300以上9999999以下で入力してください" if price.nil? || price < 300 || price > 9999999
  end

  def check_category(category,child)

app/helpers/items_helper.rb
module ItemsHelper

  def thousands_separator(price)
    "#{price.to_s(:delimited, delimiter: ',')}" if price != nil
  end

  def commission(price)
      @commission = (price * 0.1).round() if price != nil
  end

  def profits(price)
    profits = (price - @commission) if price != nil
  end

  def get_child_category(category)
    @child_category = Category.where(main_category_id: category.id).where(sub_category_id: nil)
  end

  def get_grand_child_category(category, child_category)
    @grand_child_category = Category.where(main_category_id: category.id).where(sub_category_id: child_category.id)
  end

end

app/views/items/_all-show.html.haml
.all-show-index.l-single-container
  .center-contents
    .all-show-index__title
      - if request.path_info == '/items/all_brands_show'
        %h2
          ブランド一覧
      - else
        %h2
          カテゴリー一覧
    - if request.path_info == '/items/all_categories_show'
      .category-list-menu.text-center
        - @category.each do |category|
          = link_to "##{category.id}",class: "white category-list-menu__link-name" do
            %div
              = category.name

    - @category.each do |category|
      .category-lists-boxes
        .category-lists-box.white
          .category-lists-box__root-category-name.font-white.red{id: "#{category.id}"}
            %h3
              = category.name
          .category-lists-box__inner-box
            %p
              = link_to 'すべて',category_path(category.id)
            - @child_category[category.id - 1].each do |child_category|
              .child-category-name
                %h4
                  = child_category.name
              .grand-child-category-box
                .grand-child-category-box__grand-child-category-name
                  %p
                    = link_to 'すべて',category_path(child_category.id)
                - grand_child_category = Category.where(main_category_id: category.id).where(sub_category_id: child_category.id)
                - grand_child_category.each do |grand_child_category|
                  .grand-child-category-box__grand-child-category-name
                    %p
                      = link_to category_path(grand_child_category.id) do
                        = grand_child_category.name

app/views/items/_delete-overlay.html.haml
%aside.modal.is-show.is-animate
  .modal-inner.modal-banner
    .modal-body
      .modal-head.bold
        確認

      削除すると二度と復活できません。<br>削除する代わりに停止することもできます。<br>
      <br>
      本当に削除しますか？

    .clearfix
      .modal-btn.modal-btn-cancel
        キャンセル
      = form_for @item, method: :delete do |f|
        = f.submit '削除する', class: 'modal-btn modal-btn-submit'

app/views/items/_items.html.haml
.swiper-container
  .swiper-wrapper

    .swiper-slide
      = image_tag("/images/mercari4.jpg", class: "swiper-slide__image")

    .swiper-slide
      = image_tag("/images/mercari1.jpg", class: "swiper-slide__image")

    .swiper-slide
      %div
        .top-main-visual
          .top-main-visual__div
            .top-main-visual__div__content
              %h2 スマホでかんたん<br>フリマアプリ
              %p メルカリはスマホカメラからすぐに出品できる<br>購入時も安心な独自システムのアプリです
              .top-main-visual__div__content__store.clearfix
                = link_to '#' do
                  = image_tag "app-store.svg"
                = link_to '#' do
                  = image_tag "google-play.svg"

            = image_tag "merucari-top.png", class: "top-main-visual__image"

    .swiper-slide
      = image_tag("/images/mercari3.jpg", class: "swiper-slide__image")

  .swiper-button-prev
  .swiper-button-next
  .swiper-pagination#pagination

%section.pickup-container
  %h2.pickup-container__title
    ピックアップカテゴリー

  - @category_items.zip(@category_name).each do |item, category|
    = render partial: 'shared/toppage_category_items',locals: {item: item,category: category}

  %h2.pickup-container__title
    ピックアップブランド

  - @brand_items.zip(@brand_names).each do |item, name|
    = render partial: 'shared/toppage_brand_items',locals: {item: item,name: name}

app/views/items/trading_message.html.haml
- if @item.buyer_id == current_user.id
  - breadcrumb :trading_message_buy
- else
  - breadcrumb :trading_message_sell
= render 'shared/header'

%main.l-container.clearfix
  .l-content
    %section.l-chapter-container
      %h2.l-chapter-head 取引画面
      .transact-attention
        - if @item.user_id == current_user.id
          - if @item.delivery_status == 0
            %h3
              %i.fa.fa-truck
              %span 発送をしてください
            %p 商品が購入され支払いされました。商品の発送を行ってください。
          - elsif @item.delivery_status == 1
            %h3
              %i.fa.fa-check
              %span 商品の発送を通知しました
            %p 購入者の受取確認と評価をしばらくお待ち下さい
          - elsif @item.delivery_status == 2
            %h3
              %i.fa.fa-user-circle
              %span 購入者の評価をしてください
            %p 受け取りが完了しました。購入者の評価が終わると取引完了となります。
          - elsif @item.delivery_status == 3
            %h3
              %i.fa.fa-check
              %span 取引が完了しました
            %p この度はメルカリのご利用ありがとうございました。
        - else
          - if @item.delivery_status == 0
            %h3
              %i.fa.fa-clock-o
              %span 発送をお待ちください
            %p 出品者からの発送通知をお待ちください。
          - elsif @item.delivery_status == 1
            %h3
              %i.fa.fa-user-circle
              %span 受取評価をしてください
            %p 商品が発送されました。商品が到着したら、出品者の評価をしてください。
          - elsif @item.delivery_status == 2
            %h3
              %i.fa.fa-check
              %span 受取評価をしました
            %p 出品者からの評価が終わると取引完了となります。しばらくお待ちください。
          - elsif @item.delivery_status == 3
            %h3
              %i.fa.fa-check
              %span 取引が完了しました
            %p この度はメルカリのご利用ありがとうございました。
      %ul.transact-guide.text-right
        %li
          %a{:href => "/jp/help_center/category/5/", :target => "_blank"}
            - if @item.user_id == current_user.id
              %span 商品が売れた後の流れ
              %i.fa.fa-angle-right
            - else
              %span 購入した後の流れ
              %i.fa.fa-angle-right
        %li
          %a{:href => "/jp/help_center/category/5/", :target => "_blank"}
            - if @item.user_id == current_user.id
              %span 出品者のよくある質問
              %i.fa.fa-angle-right
            - else
              %span 購入者のよくある質問
              %i.fa.fa-angle-right

      - if @item.delivery_status == 1
        %section.l-single-inner.yuuyuu-content
          %h3 配送状況
          %nav.progress-bar
            %ol.clearfix
              %li.active
                発送済み
                .progress-status
              %li
                輸送中
                .progress-status
              %li
                配達中
                .progress-status
              %li
                受取
                .progress-status
          %p 引受
          %p
            %span.bold
              ※ゆうゆうメルカリ便に関するお問い合わせは
              %a{:href => "https://www.mercari.com/jp/mypage/support/"}> こちら
              よりお願いします
            %br/
            （日本郵便には、直接お問い合わせされないようお願いします）

      - if @item.delivery_status == 1 && @item.buyer_id == current_user.id
        = form_for [@late], url: trading_page_item_path(@item.id), method: :post, html: {class: 'form transact-form-review'} do |f|
          %input{:name => "__csrf_value", :type => "hidden", :value => "548b8672d0a5998354cfac5c0af6823e6a1fd351fdac08492995fc979a866428bcdf5275bb3e1f5dce8399036f2f3b1d2edc82e5c7f7b893ca0525ae979de99fc"}/
          .checkbox-default
            %input#transaction_delivered{:name => "", :type => "checkbox", :value => "1",required: "required"}/
            %label{:for => "transaction_delivered"} 商品の中身を確認しました。
          %ul.transact-review-list.clearfix
            %li
              = f.radio_button :late, 1, required: "required"
              良い
            %li
              = f.radio_button :late, 2
              普通
            %li
              = f.radio_button :late, 3
              悪い
          %p 評価のコメントを記入しましょう。
          = f.text_area :text, class: 'message', placeholder: 'コメントはなくても構いませんが、お礼のメッセージなどを書くと喜ばれます。',required: "required"
          = f.submit "評価を投稿する", data: { disable_with: "送信中..." },class: 'button btn-default btn-red'


      - if @item.delivery_status == 2 && @item.user_id == current_user.id
        = form_for [@late], url: pay_item_path(@item.id), method: :post, html: {class: 'form transact-form-review'} do |f|
          %input{:name => "__csrf_value", :type => "hidden", :value => "548b8672d0a5998354cfac5c0af6823e6a1fd351fdac08492995fc979a866428bcdf5275bb3e1f5dce8399036f2f3b1d2edc82e5c7f7b893ca0525ae979de99fc"}/
          .checkbox-default
          %ul.transact-review-list.clearfix
            %li
              = f.radio_button :late, 1, required: "required"
              良い
            %li
              = f.radio_button :late, 2
              普通
            %li
              = f.radio_button :late, 3
              悪い
          %p 評価のコメントを記入しましょう。
          = f.text_area :text, class: 'message', placeholder: 'コメントはなくても構いませんが、お礼のメッセージなどを書くと喜ばれます。',required: "required"
          = f.submit "評価を投稿する", data: { disable_with: "送信中..." },class: 'button btn-default btn-red'



      - if @item.delivery_status == 0 && @item.user_id == current_user.id
        .transact-button
          = link_to "商品の発送をしたので、発送通知をする", trading_page_item_path(@item.id), method: :post, class:"button btn-default btn-red"

      // 取引メッセージ
      .message-container
        .message-content1
          .notification.notification-success
            %i.icon-close
          = render partial: 'shared/messages',locals: { item: @item, messages: @messages}

        .message-content2
          .message-form
            %p 取引メッセージの内容は、必要に応じて事務局で確認しています
            = form_for [@item,@message], url: message_item_path(@item.id) do |f|
              = f.text_area :text, class: 'textarea-default',required: "required"
              = f.submit "取引メッセージを送る", data: { disable_with: "送信中..." },class: 'message-submit btn-default btn-gray',id: "new-comment-submit"
        %aside.modal{"data-close" => "modal", "data-modal" => "delete-comment"}
          .modal-inner.modal-banner
            .modal-body
              .modal-head.bold 確認
              %div{"data-comment" => "body"}
              %br/
              本当にこのコメントを削除してよろしいですか？
            %form{:action => "https://www.mercari.com/jp/comment/delete/", :method => "POST"}
              .clearfix
                .modal-btn.modal-btn-cancel{"data-close" => "modal"} キャンセル
                %button.modal-btn.modal-btn-submit{:type => "submit"}
                  削除する
              %input{:name => "item_id", :type => "hidden", :value => "m18251864076"}/
              %input{:name => "comment_id", :type => "hidden", :value => ""}/
              %input{:name => "__csrf_value", :type => "hidden", :value => "a50969b0ebdc51fb05cb19bc49a1e9db2011786b93ef65c6eb24ee21407267529e12152d425a4ff8c7423eab9d587880161901ad69b4c4d8c5c9808af854f5dd6"}/
      .message-content3
        ※お困りの際は
        %a{:href => "/jp/help_center/category/1/", :target => "_blank"}> よくある質問
        をご確認ください。
    %aside.modal{"data-close" => "modal", "data-modal" => "seller-cancel"}
      .modal-inner.modal-banner
        .modal-body
          .modal-head.bold 取引をキャンセルしますか？
          キャンセル後、商品は出品停止状態になりますので、再度出品をお願いいたします
        .clearfix
          .modal-btn.modal-btn-cancel{"data-close" => "modal"} いいえ
          %form{:action => "/jp/transaction/seller_cancel/done/m18251864076/", :method => "POST", :novalidate => "novalidate"}
            %input{:name => "__csrf_value", :type => "hidden", :value => "a50969b0ebdc51fb05cb19bc49a1e9db2011786b93ef65c6eb24ee21407267529e12152d425a4ff8c7423eab9d587880161901ad69b4c4d8c5c9808af854f5dd6"}/
            %button.modal-btn.modal-btn-submit{:type => "submit"} はい
    %aside.modal{"data-close" => "modal", "data-modal" => "buyer-cancel"}
      .modal-inner.modal-banner
        .modal-body
          .modal-head.bold 取引キャンセルを依頼しますか
          事務局にて取引内容を確認後、対応してまいります
        .clearfix
          .modal-btn.modal-btn-cancel{"data-close" => "modal"} キャンセル
          %form{:action => "/jp/transaction/buyer_cancel/done/m18251864076/", :method => "POST", :novalidate => "novalidate"}
            %input{:name => "__csrf_value", :type => "hidden", :value => "a50969b0ebdc51fb05cb19bc49a1e9db2011786b93ef65c6eb24ee21407267529e12152d425a4ff8c7423eab9d587880161901ad69b4c4d8c5c9808af854f5dd6"}/
            %button.modal-btn.modal-btn-submit{:type => "submit"} はい


  .l-side
    %section.l-side-container
      %h3.transact-info-head 取引情報
      .transact-info-inner
        %ul.transact-info-table
          %li.transact-info-table-row
            %span.transact-info-table-cell 商品
            %ul.transact-info-table-cell
              %li
                = image_tag @item.item_images.first.image, class: 'img lazyloaded'
                .transact-info-item.bold
                  #{@item.name}
                  %br/
                  ¥#{@item.price}
          %li.transact-info-table-row
            %span.transact-info-table-cell 送料
            %ul.transact-info-table-cell
              %li
                - if @item.postage == 1
                  送料込み(出品者負担)
                - else
                  着払い(購入者負担)
          %li.transact-info-table-row
            %span.transact-info-table-cell 購入日時
            %ul.transact-info-table-cell
              %li #{@item.created_at.strftime("%m月%d日 %H:%M")}
          %li.transact-info-table-row
            %span.transact-info-table-cell 商品ID
            %ul.transact-info-table-cell
              %li #{@item.id}
          %li.transact-info-table-row
            %span.transact-info-table-cell お届け先
            %ul.transact-info-table-cell
              %li
                %p
                  = "〒 #{zip_code(@address.post_number)}"
                %p
                  = "#{@prefecture.name} #{@address.city} #{@address.town} #{@address.building}"
                %p
                  %span.buyer-name
                    = @buyer.nickname
                  %span.sama
                    様
    %section.l-side-container
      %h3.transact-info-head 出品者情報
      .transact-info-inner
        %a.transaction-user-icon{:href => "#"}
          %figure
            %div.image-box
              - if @item.user.persisted? && @item.user.avatar?
                = image_tag @item.user.avatar.to_s, class: 'avatar_present_img'
              - else
                = image_tag "//static.mercdn.net/images/member_photo_noimage_thumb.png", alt: ""
            %figcaption.bold
              .transact-user-name
                #{@item.user.nickname}
          %i.fa.fa-angle-right



= render 'shared/footer'