config/routes.rb
Rails.application.routes.draw do

  root 'items#index'

  get 'likes/create'
  get 'likes/destroy'

  post 'users/card_create',   to: 'users#card_create'
  delete 'users/card_delete', to: 'users#card_delete'

  match 'category_select',       to: 'items#category_select',       via: [:get, :post]
  match 'child_category_select', to: 'items#child_category_select', via: [:get, :post]

  devise_for :users, controllers: {
    registrations:      'users/registrations',
    sessions:           'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get  'to_signup',      to: 'users/registrations#to_signup'
    post 'signup/profile', to: 'users/registrations#profile'
    post 'signup/address', to: 'users/registrations#address'
    post 'signup/credit',  to: 'users/registrations#credit'
  end

  resources :users,except: :show do
    get :logout,               on: :collection
    get :payment_method,       on: :collection
    get :card_registration,    on: :collection
    get :indentification,      on: :collection
    get :trading,              on: :collection
    get :purchased,            on: :collection
    get :exhibition,           on: :collection
    get :seller_trading,       on: :collection
    get :sold_page,            on: :collection
    get :notification,         on: :collection
    get :todo,                 on: :collection
    get :individual,           on: :member
    resources :likes,     only: :index
    resources :addresses, only: [:edit, :update]
    resources :lates,     only: :index do
      get :great,              on: :collection
      get :good,               on: :collection
      get :poor,               on: :collection
    end
    member do
     get :following, :followers
    end
  end

  scope :profiels do
    resources :users, only: :show
  end

  resources :items do
    get  :buy,                 on: :collection
    get  :all_categories_show, on: :collection
    get  :item_search_result,  on: :collection
    get  :buy,                 on: :member
    post :pay,                 on: :member
    get  :trading_message,     on: :member
    post :trading_page,        on: :member
    post :message,             on: :member
    post :late,                on: :member
    resources :comments, only: [:create, :destroy]
    resources :likes,    only: [:create, :destroy]
  end

  resources :categories, only: :show do
    get :child_category,       on: :collection
    get :grand_child_category, on: :collection
  end

  resources :brands, only: :show do
    get :brand_show,          on: :member
  end

  resources :relationships, only: [:create, :destroy]

end

app/models/brand.rb
class Brand < ApplicationRecord

  has_many :items
  has_many :category_brands
  has_many :categories, through: :category_brands
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  before_action :category_in_brand, only: [:show, :brand_show]
  before_action :set_search,        only: [:show, :brand_show]
  before_action :set_category,      only: [:show, :brand_show]

  def show
    @category_index = Category.find(params[:id])
    @brands = @category_index.brands
    # initialカラムのみを配列で取り出し、同じものは省く
    @initials = @brands.pluck(:initial).uniq
  end

  def brand_show
    @brand = Brand.find(params[:id])
    @items = @brand.items
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/brand_show.html.haml
- breadcrumb :brand_show, @brand

= render 'shared/header'

.lists-container
  .lists-container__full-width
    %ul.category-links


    %secttion.item-lists
      %h1.item-lists__title
        #{@brand.name}の商品一覧
      - if @items.length > 0
        .item-lists__item-container
          = render partial: 'shared/category_items', locals: {items: @items}
      - else
        商品がありません

.spacial-description
  .spacial-description__title
    %h3
      = @brand.name
  .spacial-description__text
    %p
      - if @brand.intro
        = @brand.intro

- if @items.length > 0
  = paginate @items


= render 'shared/sell-button'

= render 'shared/footer'

app/views/brands/show.html.haml
- breadcrumb :all_brands_show
= render 'shared/header'

%main.l-container.clearfix
  .brand-wrapper
    .brand-index.clearfix
      %h2 ブランド一覧

      .category-container.clearfix
        - @categories.each do |category|
          = link_to brand_path(category.id) do
            = category.name


      .brand-initial-container.clearfix
        - @initials.each do |initial|
          .initial__box.clearfix
            %a{href: "##{initial}"}
              %p
              = initial

      .brand-name-container
        .category-name
          %h3
            = @category_index.name

        .brand-name-list
          - @initials.each do |initial|
            .brand-name__initial{id: "#{initial}"}
              %h4
                = initial

            .brand-name__wrapper
              - @brands.each do |brand|
                - if initial == brand.initial
                  .brand-name__box--left
                    = link_to brand_show_brand_path(brand.id), class: "brand-name-link" do
                      .brand-name
                        %div
                          %p
                            = brand.name

= render 'shared/footer'

= render 'shared/sell-button'